---
language: python
python: "2.7"
dist: trusty

sudo: required

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible

script:
  - ansible-playbook tests/test.yml -i tests/inventory
